name: Generic AMD64
##### https://www.balena.io/docs/reference/base-images/base-images-ref/####

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  Build-Generic-AMD64-Container:
    uses: fraunhofer-ipa-oe420/github-templates/.github/workflows/balenaimg_gitrepo.yml@main
    with:
      aarch_version: generic
